Added new Shunk with updated appearance, actuated chuck and action fo…
fetchrobotics/fetch_gazebo pull request #89
Opened 2019-05-03 18:28 UTC by RDaneelOlivav

…r open and close and start operation and end operation. Also decoupled shunk controllers from action.
This is an update for the shunk machine. In theory, to use it, the action server has to be called for opening and closing the chuck. And also for staring the operation which won't allow opening the chuck and stopping the operation once it has started.
Also, added models with simplified collisions to maximize the grasping ability of the parts, although not tested, because thats another step.

2019-05-03 21:55 UTC, moriarty commented
I will just close and re-open this to trigger the Build.

2019-05-03 22:12 UTC, moriarty requested changes
1. There is a `.pyc` file which shouldn't be checked in.
2. Why did the `cmake_minimum_required` version change?
3. Is there now an additional action which must be called? START_OPERATION and END_OPERATION ? @velveteenrobot should take a look and see if this is really required we were going to just start the operation timer as soon as "close" was called.

2019-05-03 22:12 UTC, moriarty commented on fetchit_challenge/action/SchunkMachine.action
> +uint32 START_OPERATION=2
@velveteenrobot can you review this

2019-05-03 22:12 UTC, moriarty commented on fetchit_challenge/nodes/shunk_machine_controlers.py
> +        pass
The `.pyc` file shouldn't be checked in. it's the next file in the PR

2019-05-06 07:16 UTC, ben-fido commented
This is very good @RDaneelOlivav , it works now.  
Thanks!

.

### Important things to fix:

**Add this to package.xml**
```
<exec_depend>joint_state_controller</exec_depend>
<exec_depend>position_controllers</exec_depend>
```

.

**Edit this file:**  
`schunk_machine_server.py`  
This node is already started under namespace `"schunk_machine"`, so the server path should be `"chuck"`
like this:  
```
self.server = actionlib.SimpleActionServer('chuck', SchunkMachineAction, self.callback, False)
```

.

**Add a new launch file:**  
`shunk_machine_start_server_real.launch`
containing this code:  
```
    <group ns="schunk_machine">
        <arg name="shunk_version" />
        <node name="shunk_machine_server" pkg="fetchit_challenge" type="schunk_machine_server.py"
              respawn="false" output="screen" />
    </group>
```

.

**Change axis origin of the door visual and collision mesh:**  
The axis origin of the sliding door is down near the floor.
Can you edit the mesh file so the axis is aligned with one edge of the part?
Then change the link offset in URDF file.
This will make it easier to fix the inertia values for physics simulation, so the door moves better.

.

Then @velveteenrobot  needs to edit her sample scripts:  
```
open_schunk_machine.py
close_schunk_machine.py
```
to send action messages to `"/schunk_machine/chuck"`

.

### Minor suggestions:

**Schunk logo** disappeared from door.

.

Rename joints:  
```
lathe_gripper1_joint
lathe_gripper2_joint
lathe_gripper3_joint
```
to be:  
```
chuck_joint1
chuck_joint2
chuck_joint3
```
because there is one thing with 3 joints.

.

2019-05-08 17:05 UTC, moriarty commented
@velveteenrobot I'm going to merge this.

The Schunk Machine is being packed today I don't know if we'll get a chance to test it but we'll have one day in Montreal before the teams arrive.

2019-05-08 17:05 UTC, moriarty approved these changes

2019-05-08 17:08 UTC, merged